### ISSUE TITLE
Is the scraper polite?

### ISSUE THREAD

**Issue by simison** [mrkvon/trustroots-graph#1]
Hey! Interesting.

Is the scraper configured to be polite, as in, not to cause too much stress to our server? Basically, can it accidentally cause a DoS attack?

I'd be interested to get some help from you to create any stats you'd like to see directly from our DB. Let's talk more. :-)

**Comment by mrkvon** [comment]
Hello Mikael,
I've done some unintentional DoS during the development. I'm sorry for that.
As it is now, the scraper performs only one request (user + her connections) when the previous request is finished. So the running time is a couple of minutes and I hope it shouldn't cause problems.
