### ISSUE TITLE
Shortest path between users

### ISSUE THREAD

**Issue by simison** [mrkvon/trustroots-graph#2]
I would be very interested to see something like this done on trustroots.org between two users directly from our DB.

An example from Linkedin:
![image](https://cloud.githubusercontent.com/assets/87168/14060797/f98cd54c-f377-11e5-92ac-6c6250db8b6d.png)

Thoughts?

**Comment by mrkvon** [comment]
Some [algorithms](http://www.cs.cornell.edu/courses/cs312/2002sp/lectures/lec20/lec20.htm) for searching shortest path in graph can be used.

These algorithms are generally quite expensive (and getting worse as the graph grows). One has to go through connections of the source user and then through connections of these connections etc. until the target user is found (breadth-first search). So the running time and using of resources is the main limit of this, i believe.

Document databases (i.e. mongodb used by trustroots) don't have a native support for graph algorithms, but it can be implemented in node.

Some solutions for expensiveness can be:
- stopping the search after a certain depth is reached (i.e. look for max. 2 people long connections)
- keep a parallel graph database for this purpose (just with usernames and connections) and make the searches natively in it
- some caching???
- ...research needed for more

That's briefly how i understand the problem.

I'm a dilettante fan of graphs, and would be interested in helping with this. Can't promise it or any specific time at the moment. Let's discuss if you wish. :)

**Comment by simison** [comment]
I was thinking this another day. Actually, being pragmatic, it mostly makes sense to know if user A has common friends with user B. The rest goes to "nice to know" category but not really useful in terms of understanding if that person is gonna be more similar to me, or if user A can ask someone to introduce them to user B... summa summarum; not worth the hassle?

**Comment by mrkvon** [comment]
You're probably right. And showing common friends means just comparing their lists of connections, so it's easy if somebody decides to do it.

I just noticed cs reintroduced this feature recently.

**Comment by simison** [comment]
Yep, it's a smart move from them.
